# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: GitHub CI

on: [push, pull_request]

jobs:
  build:
    name: Verify
    uses: apache/maven-gh-actions-shared/.github/workflows/maven-verify.yml@v3
    with:
      ff-goal: '-Drat.skip=true -P run-its verify'         # site use project version for reporting
      verify-goal: '-Drat.skip=true -P run-its verify'     # should be the same as for first build
